### ISSUE TITLE
Sensor refresh frequency is not consistent

### ISSUE THREAD

**Issue by dsv591** [dahlb/ha_blueair#10]
Sometimes it's 3 hours, sometimes it's one

![imagen](https://user-images.githubusercontent.com/8061730/215651420-a77e061a-0d19-47a7-af4c-108159fec8e9.png)

Seems to be the same for all sensors

![imagen](https://user-images.githubusercontent.com/8061730/215651506-35e5ba80-e04c-41ac-82c8-4841b11e1b9b.png)

**Comment by dahlb** [comment]
Those screenshots show approximately when device says the value changed for each of those sensors.  That is different then when the device was last asked what the sensors' value is, to see that you can look at the api debug logs to see the logged time stamps with the calls to the API
