### ISSUE TITLE
Errors after 2024.8 - FanEntityFeature.X

### ISSUE THREAD

**Issue by jhemak** [dahlb/ha_blueair#115]
Errors in logs after 2024.8 installed:

`[homeassistant.components.fan] Entity None (<class 'custom_components.ha_blueair.fan.BlueairAwsFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/dahlb/ha_blueair/issues`

`[homeassistant.components.fan] Entity None (<class 'custom_components.ha_blueair.fan.BlueairAwsFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/dahlb/ha_blueair/issues`

**Comment by dahlb** [comment]
thanks for writing this up so quickly.

1.9.3 was released to address the new feature flags added in 2024.8
