### ISSUE TITLE
5440i - Child Lock?

### ISSUE THREAD

**Issue by digitalurban** [dahlb/ha_blueair#116]
Setting up for a 5440i - i get the error 

Logger: custom_components.ha_blueair.blueair_data_update_coordinator
Source: custom_components/ha_blueair/blueair_data_update_coordinator.py:40
integration: Blueair ([documentation](https://github.com/dahlb/ha_blueair), [issues](https://github.com/dahlb/ha_blueair/issues))
First occurred: 2:33:15 PM (17 occurrences)
Last logged: 2:45:24 PM

'child_lock'

I can't seem to get any further. Any help would be great.

Andy

**Comment by dahlb** [comment]
1.9.4 should better handle models that don't support child locks, but if it isn't resolved please attach debug logs as outlined in the readme of this repo
