### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by lautenbach** [dahlb/ha_blueair#141]
Error message when attempting to sign in: Failed setup, will retry: 'NoneType' object has no attribute 'json'

![CleanShot 2024-11-25 at 10 38 41@2x](https://github.com/user-attachments/assets/f3041df9-34be-43fe-b3f0-1a5a5a517254)

have tried:
* re-downloading ha_blueair
* changing blueair password (log out, log in)
* removing filters from account, re-adding
* rebooting filters
* switching from us to eu server

**Comment by dahlb** [comment]
we'd need you debug enabled logs to help you understand this error.
see guidelines at
https://github.com/dahlb/ha_blueair#troubleshooting

**Comment by lautenbach** [comment]
This issue resolved (but not sure how/why)
