### ISSUE TITLE
Support for 211i?

### ISSUE THREAD

**Issue by jef-pearlman** [dahlb/ha_blueair#145]
Would it be possible to add support for the 211i?  The integration currently recognizes the device, but some sensors don't work (in part because they don't exist on this device) and others don't match the device (e.g., pm1/10/25 all read the same value, which does not match the device's display or app).  

I turned on debug logging and am happy to provide the log, though I wasn't sure what stuff was sensitive (API keys, etc.).  Below is the pair of HTTP responses that seemed most relevant with the obvious pieces redacted.  Please let me know if what else would be helpful, and no problem if you can't add this in.  Thanks for all your work on this!

`2024-12-01 11:29:13.628 DEBUG (MainThread) [blueair_api.util_http] response json: {'appConfig': {}, 'identityconfig': {}, 'deviceInfo': [{'id': '[ID REDACTED]', 'configuration': {'df': {'a': 877, 'ot': 'B4Filter', 'fsfc': 12000000, 'alg': 'FilterAlg1'}, 'di': {'cfv': '1.1.7', 'cma': 'cc:7b:5c:ea:6c:d0', 'mt': '4', 'name': 'Guest bedroom ', 'sku': '110059', 'mfv': '1.1.7', 'ofv': '1.1.7', 'hw': 'nb_h_1.0', 'ds': '[DS REDACTED]'}, '_ot': 'CmConfig', '_f': False, '_it': 'urn:blueair:openapi:version:blue:0.0.5', '_eid': '[_EID REDACTED]', '_sc': 'Instance', 'ds': {'fu0': {'tf': 'senml+json', 'ot': 'FU', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/fu0', 'ttl': -1, 'n': 'fu0', 'fe': True}, 'rssi': {'tf': 'senml+json', 'ot': 'RSSI', 'e': False, 'i': 60000, 'tn': 'd/[ID REDACTED]/s/rssi', 'ttl': 600, 'n': 'rssi', 'fe': True}, 'ledb': {'tf': 'senml+json', 'ot': 'Led', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/ledb', 'ttl': -1, 'n': 'ledb', 'fe': True}, 'chl': {'tf': 'senml+json', 'ot': 'ChildLock', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/chl', 'ttl': -1, 'n': 'chl', 'fe': True}, 'pm10': {'tf': 'senml+json', 'ot': 'PM10', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/pm10', 'ttl': 0, 'n': 'pm10', 'fe': True}, 'is': {'tf': 'senml+json', 'ot': 'IonizerState', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/is', 'ttl': -1, 'n': 'is', 'fe': True}, 'am': {'tf': 'senml+json', 'ot': 'AutoMode', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/am', 'ttl': -1, 'n': 'am', 'fe': True}, 'sb': {'tf': 'senml+json', 'ot': 'Standby', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/sb', 'ttl': -1, 'n': 'sb', 'fe': True}, 'rt5m': {'tf': 'senml+json', 'ot': 'RT5m', 'e': False, 'i': 300000, 'tn': 'd/[ID REDACTED]/s/5m', 'sn': ['pm2_5', 'fsp0', 'rssi', 'pm1', 'pm10'], 'ttl': 1200, 'n': 'rt5m', 'fe': True}, 'rt1s': {'tf': 'senml+json', 'ot': 'RT1s', 'e': False, 'i': 1000, 'tn': 'd/[ID REDACTED]/s/1s', 'sn': ['pm2_5', 'fsp0', 'rssi', 'pm1', 'pm10'], 'ttl': 0, 'n': 'rt1s', 'fe': True}, 'rt5s': {'tf': 'senml+json', 'ot': 'RT5s', 'e': False, 'i': 5000, 'tn': 'd/[ID REDACTED]/s/5s', 'sn': ['pm2_5', 'fsp0', 'rssi', 'pm1', 'pm10'], 'ttl': 1200, 'n': 'rt5s', 'fe': True}, 'pm1': {'tf': 'senml+json', 'ot': 'PM1', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/pm1', 'ttl': 0, 'n': 'pm1', 'fe': True}, 'pm2_5': {'tf': 'senml+json', 'ot': 'PM2_5', 'e': False, 'i': 60000, 'tn': 'd/[ID REDACTED]/s/pm2_5', 'ttl': 1200, 'n': 'pm2_5', 'fe': True}, 'b5m': {'tf': 'senml+json', 'th': ['5kb', '4h'], 'ot': 'Batch5m', 'e': True, 'i': 300000, 'tn': '$aws/rules/telemetry_ingest_rule/d/[ID REDACTED]/s/batch/b5m', 'sn': ['pm2_5', 'fsp0', 'rssi', 'pm1', 'pm10'], 'ttl': -1, 'n': 'b5m', 'fe': True}, 'sp': {'tf': 'senml+json', 'ot': 'SensorBoxPresense', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/sp', 'ttl': -1, 'n': 'sp', 'fe': True}, 'fsp0': {'st': 'fsp0', 'tf': 'senml+json', 't': 10, 'ot': 'Fanspeed', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/fsp0', 'sn': ['fsp0'], 'ttl': -1, 'n': 'fsp0', 'fe': True}, 'nm': {'tf': 'senml+json', 'ot': 'NightMode', 'e': True, 'i': 0, 'tn': 'd/[ID REDACTED]/s/nm', 'ttl': -1, 'n': 'nm', 'fe': True}}, '_r': 'us-east-2', '_s': {'sig': '[SIG REDACTED]', 'salg': 'SHA256'}, '_t': 'Diff', '_v': 1730068331, '_cas': 1722915498, '_id': '[ID REDACTED]', 'fc': {'pwd': '[PWD REDACTED]', 'ssid': 'BAFactory', 'url': ' '}, 'da': {'reboot': {'p': True, 'a': False, 'ot': 'Reboot', 'e': True, 'tn': 'd/[ID REDACTED]/a/reboot', 'n': 'reboot', 'fe': True}, 'uitest': {'p': False, 'a': 'off', 'ot': 'UiTest', 'e': True, 'tn': 'd/[ID REDACTED]/a/uitest', 'n': 'uitest', 'fe': True}, 'ledb': {'p': True, 'a': 100, 'tf': 'senml+json', 'ot': 'LedBrightness', 'e': True, 'tn': 'd/[ID REDACTED]/a/ledb', 'n': 'ledb', 'fe': True}, 'chl': {'p': True, 'a': False, 'tf': 'senml+json', 'ot': 'ChildLock', 'e': True, 'tn': 'd/[ID REDACTED]/a/chl', 'n': 'chl', 'fe': True}, 'sflu': {'p': False, 'a': False, 'ot': 'SensorFlush', 'e': True, 'tn': 'd/[ID REDACTED]/a/sflu', 'n': 'sflu', 'fe': True}, 'buttontest': {'p': False, 'a': False, 'ot': 'ButtonTest', 'e': True, 'tn': 'd/[ID REDACTED]/a/buttontest', 'n': 'buttontest', 'fe': True}, 'is': {'p': False, 'a': False, 'tf': 'senml+json', 'ot': 'IonizerState', 'e': True, 'tn': 'd/[ID REDACTED]/a/is', 'n': 'is', 'fe': True}, 'am': {'p': True, 'a': False, 'tf': 'senml+json', 'ot': 'AutoMode', 'e': True, 'tn': 'd/[ID REDACTED]/a/am', 'n': 'am', 'fe': True}, 'fsp0': {'p': True, 'st': 'fsp0', 'a': 11, 'tf': 'senml+json', 'ot': 'Fanspeed', 'e': True, 'tn': 'd/[ID REDACTED]/a/fsp0', 'n': 'fsp0', 'fe': True}, 'sb': {'p': True, 'a': False, 'tf': 'senml+json', 'sbt': 'sensor_on', 'ot': 'Standby', 'e': True, 'tn': 'd/[ID REDACTED]/a/sb', 'n': 'sb', 'fe': True}, 'nm': {'p': True, 'maxfsp': 23, 'a': False, 'tf': 'senml+json', 'ot': 'NightMode', 'ledb': 12, 'e': True, 'tn': 'd/[ID REDACTED]/a/nm', 'n': 'nm', 'fe': True}}, 'dc': {'cfv': {'d': 'di.cfv', 't': 'integer', 'v': 0, 'n': 'cfv'}, 'filterusage': {'s': 'fu0', 't': 'integer', 'v': 0, 'n': 'filterusage'}, 'brightness': {'a': 'ledb', 's': 'ledb', 't': 'integer', 'v': 100, 'n': 'brightness'}, 'standby': {'a': 'sb', 's': 'sb', 't': 'boolean', 'v': False, 'n': 'standby'}, 'fanspeed': {'a': 'fsp0', 's': 'fsp0', 't': 'integer', 'v': 11, 'n': 'fanspeed'}, 'nightmode': {'a': 'nm', 's': 'nm', 't': 'boolean', 'v': False, 'n': 'nightmode'}, 'childlock': {'a': 'chl', 's': 'chl', 't': 'boolean', 'v': False, 'n': 'childlock'}, 'mfv': {'d': 'di.mfv', 't': 'integer', 'v': 0, 'n': 'mfv'}, 'ofv': {'d': 'di.ofv', 't': 'integer', 'v': 0, 'n': 'ofv'}, 'automode': {'a': 'am', 's': 'am', 't': 'boolean', 'v': False, 'n': 'automode'}}}, 'alarms': [], 'events': [], 'sensordata': [{'v': '0', 'n': 'pm2_5', 't': 1733068936}, {'v': '11', 'n': 'fsp0', 't': 1733068936}, {'v': '-42', 'n': 'rssi', 't': 1733068936}, {'v': '0', 'n': 'pm1', 't': 1733068936}, {'v': '0', 'n': 'pm10', 't': 1733068936}], 'states': [{'n': 'cfv', 'v': 16777479, 't': 1730513808}, {'n': 'filterusage', 'v': 13, 't': 1733057170}, {'n': 'brightness', 'v': 100, 't': 1733070689}, {'n': 'standby', 'vb': False, 't': 1732119710}, {'n': 'nightmode', 'vb': False, 't': 1732120266}, {'n': 'childlock', 'vb': False, 't': 1730513808}, {'n': 'mfv', 'v': 16777479, 't': 1730513808}, {'n': 'ofv', 'v': 16777479, 't': 1730513808}, {'n': 'automode', 'vb': True, 't': 1732638671}, {'n': 'fanspeed', 'v': 11, 't': 1732638671}, {'t': 1732638671, 'vb': True, 'n': 'online'}], 'welcomehome': {'setting': []}, 'fleet_info': [], 'location_id': '', 'timezone': 'America/Los_Angeles'}]}`
...
`2024-12-01 11:29:13.629 DEBUG (MainThread) [blueair_api.device_aws] refreshed blueair device aws: {'uuid': '[UUID REDACTED]', 'name': 'Guest bedroom ', 'type_name': 'NB', 'sku': '11 0059', 'name_api': '[NAME_API REDACTED]', 'mac': '[MAC REDACTED}', 'firmware': '1.1.7', 'mcu_firmware': '1.1.7', 'serial_number': '[SERIAL_NUMBER REDACTED]', 'brightness': 100, 'chil d_lock': False, 'fan_speed': 11, 'fan_auto_mode': True, 'running': True, 'night_mode': False, 'germ_shield': None, 'pm1': 0, 'pm2_5': 0, 'pm10': 0, 'tVOC': None, 'temperature': None, 'humidity': None, ' filter_usage': 13, 'wick_usage': None, 'wick_dry_mode': None, 'auto_regulated_humidity': None, 'water_shortage': None}`

**Comment by jef-pearlman** [comment]
And in case it's helpful, here's a screenshot of the device in HA and a [link to the device page](https://www.blueair.com/us/shop/air-purifiers/blue-pure-211i-max/3541.html?cgid=air-purifiers#start=1).
![image](https://github.com/user-attachments/assets/9b413ba4-fb8f-409f-bf6f-689fb29114bd)

**Comment by mediacutlet** [comment]
Second this! I recently acquired a 211i and would love to have the full feature set opened up in HA. Totally understand if its not doable or you don't have the time but let us know how we can help. Happy to provide a debug log if @jef-pearlman 's lacks anything.

**Comment by dahlb** [comment]
I added 211i as a recognized type in 1.11.3 and likely set the speed of the fan so that 100 in ha means 100 in the app.

As for the sensors if one of you could help me by adding a copy of the debug log like above but also include a screenshot of the app and ha sensors around the same time so I can see the data inconsistencies and the accurate versions I should be able to fix the sensors too

**Comment by mediacutlet** [comment]
Thanks @dahlb you rock. I tried to time the screenshot and debug log as closely as possible but I'm not 100% sure I nailed it to the second. It should be very, very close though.
![IMG_6282](https://github.com/user-attachments/assets/d8ba951e-a07d-40a8-af89-cddf00da0df9)

App values at 09:42 AM:
- PM1: 6
- PM2.5: 9
- PM10: 12

Home Assistant debug log values at 09:42 AM:
- PM1: 9
- PM2.5: 12
- PM10: 16

I don't believe the device has hardward to support these: Temperature, humidity, and VOC



`"sensordata": [
    {"v": "9", "n": "pm1", "t": 1733323219},
    {"v": "12", "n": "pm2_5", "t": 1733323219},
    {"v": "16", "n": "pm10", "t": 1733323219}
]
`

`"states": [
    {"n": "brightness", "v": 0, "t": 1733322593},
    {"n": "fanspeed", "v": 11, "t": 1733323322},
    {"n": "automode", "vb": true, "t": 1733323375}
]
`

Here is the full log:

`2024-12-04 09:42:59.088 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2024-12-04 09:42:59.124 DEBUG (MainThread) [blueair_api.util_http] response json: {
    "appConfig": {},
    "identityconfig": {},
    "deviceInfo": [
        {
            "id": "1155e15c-914e-4f62-b3d9-f40bde9b7e26",
            "configuration": {
                "df": {
                    "a": 877,
                    "ot": "B4Filter",
                    "fsfc": 12000000,
                    "alg": "FilterAlg1"
                },
                "di": {
                    "cfv": "1.1.7",
                    "cma": "[REDACTED: MAC Address]",
                    "mt": "4",
                    "name": "Landing",
                    "sku": "110059",
                    "mfv": "1.1.7",
                    "ofv": "1.1.7",
                    "hw": "nb_h_1.0",
                    "ds": "[REDACTED: Serial Number]"
                },
                "_ot": "CmConfig",
                "_f": false,
                "_it": "urn:blueair:openapi:version:blue:0.0.5",
                "_eid": "[REDACTED: Entity ID]",
                "_sc": "Instance",
                "ds": {
                    "fu0": {
                        "tf": "senml+json",
                        "ot": "FU",
                        "e": true,
                        "i": 0,
                        "tn": "d/1155e15c-914e-4f62-b3d9-f40bde9b7e26/s/fu0",
                        "ttl": -1,
                        "n": "fu0",
                        "fe": true
                    },
                    ...
                    "pm10": {
                        "tf": "senml+json",
                        "ot": "PM10",
                        "e": true,
                        "i": 0,
                        "tn": "d/1155e15c-914e-4f62-b3d9-f40bde9b7e26/s/pm10",
                        "ttl": 0,
                        "n": "pm10",
                        "fe": true
                    },
                    ...
                },
                "_r": "us-east-2",
                "_s": {
                    "sig": "[REDACTED: Signature]",
                    "salg": "SHA256"
                },
                "_t": "Diff",
                "_v": 1733196819,
                "_cas": 1728125377,
                "_id": "1155e15c-914e-4f62-b3d9-f40bde9b7e26",
                "fc": {
                    "pwd": "[REDACTED: Factory Password]",
                    "ssid": "[REDACTED: SSID]",
                    "url": ""
                },
                ...
            },
            ...
        }
    ],
    "sensordata": [
        {"v": "12", "n": "pm2_5", "t": 1733323219},
        {"v": "11", "n": "fsp0", "t": 1733323219},
        {"v": "-38", "n": "rssi", "t": 1733323219},
        {"v": "9", "n": "pm1", "t": 1733323219},
        {"v": "16", "n": "pm10", "t": 1733323219}
    ],
    ...
    "states": [
        {"n": "cfv", "v": 16777479, "t": 1733196795},
        {"n": "filterusage", "v": 0, "t": 1733196795},
        {"n": "brightness", "v": 0, "t": 1733322593},
        {"n": "standby", "vb": false, "t": 1733196936},
        {"n": "nightmode", "vb": false, "t": 1733311901},
        {"n": "childlock", "vb": false, "t": 1733196795},
        {"n": "mfv", "v": 16777479, "t": 1733196795},
        {"n": "ofv", "v": 16777479, "t": 1733196795},
        {"n": "automode", "vb": true, "t": 1733323375},
        {"n": "fanspeed", "v": 11, "t": 1733323322},
        {"n": "online", "vb": true, "t": 1733323322}
    ],
    ...
}
2024-12-04 09:42:59.153 DEBUG (MainThread) [blueair_api.http_aws_blueair] response 200
2024-12-04 09:42:59.154 DEBUG (MainThread) [blueair_api.callbacks] Landing publishing updates
2024-12-04 09:42:59.157 DEBUG (MainThread) [blueair_api.device_aws] refreshed blueair device aws: DeviceAws(
    api=<blueair_api.http_aws_blueair.HttpAwsBlueair object at [REDACTED]>,
    uuid="1155e15c-914e-4f62-b3d9-f40bde9b7e26",
    name="Landing",
    mac="[REDACTED: MAC Address]",
    type_name="NB",
    sku="110059",
    firmware="1.1.7",
    mcu_firmware="1.1.7",
    serial_number="[REDACTED: Serial Number]",
    brightness=0,
    child_lock=False,
    fan_speed=11,
    fan_auto_mode=True,
    running=True,
    night_mode=False,
    germ_shield=None,
    pm1=9,
    pm2_5=12,
    pm10=16,
    tVOC=None,
    temperature=None,
    humidity=None,
    filter_usage=0,
    wifi_working=True,
    wick_usage=None,
    wick_dry_mode=None,
    water_shortage=None,
    auto_regulated_humidity=None
)
2024-12-04 09:42:59.157 DEBUG (MainThread) [custom_components.ha_blueair.blueair_aws_data_update_coordinator] Finished fetching ha_blueair-Landing data in 0.604 seconds (success: True)
`


Thank you again! 🍻

**Comment by dahlb** [comment]
[1.12.2](https://github.com/dahlb/ha_blueair/commit/7f81411e18cf41dd38703e2938de27f237062457) 
removes temperature, humidity, and voc sensors from the 211 models in ha.
based on the values you saw in ha and blueair I made a formula to translate based on the api logic already identified for fan speed, my pm values are always 0 so I haven't really exercised that sensor.  Please let me know if the formula continues to hold up as the values change. thanks for all your information

**Comment by jef-pearlman** [comment]
Awesome; thanks!  It's definitely working a lot better.  I _suspect_ the scaling is a little off, but I'm having a little trouble verifying because of the long polling period and trying to make sure I get the matching data from the app and HA.   (I assumed it was 5 minutes, but based on the last release notes, I'm guessing it wasn't but is now.)  I realize that's an API limitation.  Any suggestions on getting matching data?

If my understanding is right, the HA integration updates from the API every 5 minutes, but the API updates its data every 5 minutes on a _different_ clock, meaning when HA updates the data that data will be between 0 and 5 minutes old semi-randomly.  

Is that right?  If so, any tips on getting the updates more quickly so I can match it to the app when it is actually retrieved (e.g., by increasing the polling rate temporary)?  And sorry if I'm missing something here.  Thanks!

**Comment by dahlb** [comment]
if you want to poll extra use 
```
action: homeassistant.update_entity
data:
  entity_id:
    - fan.bedroom_fan
```
more discussion of this is in https://github.com/dahlb/ha_blueair/issues/98
