### ISSUE TITLE
1.11.3 - AttributeError: 'Device' object has no attribute 'timezone'

### ISSUE THREAD

**Issue by darth-pika-hu** [dahlb/ha_blueair#151]
1.11.3 breaks Blueair Classic 205. Downgrade to 1.11.2 fixed the issue. Here is the error message:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_blueair/init__.py", line 74, in async_setup_entry
    , devices = await getdevices(
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/blueair_api/util_bootstrap.py", line 40, in get_devices
    list(devices),
    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/blueair_api/util_bootstrap.py", line 30, in create_device
    return Device(
           ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/blueair_api/device.py", line 43, in init
    _LOGGER.debug(f"creating blueair device: {self}")
                                             ^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 262, in wrapper
    result = user_function(self)
             ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in repr
AttributeError: 'Device' object has no attribute 'timezone'

**Comment by alexkrishnan** [comment]
I am experiencing the same issue with the same device (same stack trace). A downgrade fixes the issue for me as well. I suspect the bump from blueair-api from 1.13.0 to 1.15.0 to be the culprit. https://github.com/dahlb/ha_blueair/commit/88a9eb6193ddf062e9190252a52af6aa5ca272bc#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L3

**Comment by darth-pika-hu** [comment]
> I am experiencing the same issue with the same device (same stack trace). A downgrade fixes the issue for me as well. I suspect the bump from blueair-api from 1.13.0 to 1.15.0 to be the culprit. [88a9eb6#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L3](https://github.com/dahlb/ha_blueair/commit/88a9eb6193ddf062e9190252a52af6aa5ca272bc#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L3)

Yes, I have submitted a fix for the author to review.

**Comment by dahlb** [comment]
fix pushed out in 1.11.4, thanks @darth-pika-hu

**Comment by SoccerCore11** [comment]
Still same 'timezone' error message on v1.11.5

**Comment by dahlb** [comment]
verified fix for this issue in 1.11.6, sorry I didn't have time to verify the optimistic release earlier
