### ISSUE TITLE
Failed Setup - Device Object has no attribute 'timezone'

### ISSUE THREAD

**Issue by brianGit78** [dahlb/ha_blueair#152]
After the latest update I get the following error message Failed Setup - Device Object has no attribute 'timezone'. I am unable to control my blue air items (I have six units). I tried removing and adding the integration again and still the problem persists.

**I believe this may be due to having a BlueAir Classic 205**, which does not seem to have a Time Zone field in the Product Settings page and a recent change to your code may be expecting this attribute.

I am available to debug if needed.

**Comment by SoccerCore11** [comment]
For added context, with the latest update my Classic 680i is working now when previously had this error message.

**Comment by brianGit78** [comment]
Totally didn't see 1.11.6. Updated and it's all working now. Thanks and fantastic work on this integration!
