### ISSUE TITLE
Pm25 data "unavailable" as of this morning's update

### ISSUE THREAD

**Issue by benkayuk** [dahlb/ha_blueair#153]
As title. Pm25 sensor showing "unavailable" in HomeAssistant....confirm sensor data still showing in the BlueAir iOS app.

Seems to coincide with an integration update that took place this morning.

Model DustMagnet 5240i

**Comment by dahlb** [comment]
please provide your 

ha integration version
blueair device model(s)
debug logs
and a screenshot of the device in HA

**Comment by jhemak** [comment]
Hello @dahlb, I've lost PM2.5 again and moving to version 1.17.2.
