### ISSUE TITLE
Add support for 7440i (Fan speed is wrong)

### ISSUE THREAD

**Issue by shlomki** [dahlb/ha_blueair#155]
The fan speed on home assistant is usually showing the wrong value. The 7440i model has three speeds on the device, and on the app it shows a scale of 0 to 3, where you could set the slider anywhere in the scale between 1 and 3 (not just a round number). And 0 means fan off while the device is still on.

But when setting the speed to 3, home assistant shows 91% (I expected 100%).
When setting to 2, HA shows 51% (I expected 50% but I guess this is ok).
When setting to 1, HA shows 11% (I expected 1%).

The funny thing is that even when I set to 100% from HA, after a couple of seconds it updates itself to 91%.

It's probably just a problem with how the integration reads the values.

**Comment by SoccerCore11** [comment]
The Classic 680i that was just added actually has 3 fan speeds plus off also. (High, Medium, Low, Off). Currently in the integration, it's On/Off only.

**Comment by dahlb** [comment]
@SoccerCore11 please open a separate ticket for the fan issue on classic 680i

**Comment by dahlb** [comment]
@shlomki the 7440i model is still not defined within this integration, in order to provide model specific behavior I need to know the sku for 7440i models, can you add your debug logs or just search for the sku in your logs and add it here.

**Comment by shlomki** [comment]
Sure!
So the SKU shows as: `'sku': '105820'`

It appears that the response JSON actually returns the speed as raw values of 91, 51 or 11 as I previously mentioned. The numbers could be different if I set a specific speed in the app (anywhere between 1,2,3). These values do not appear to be percentages, but the integration takes them as-is and presents them as fan speed percentage:
`'fanspeed': {'a': 'fsp0', 's': 'fsp0', 't': 'integer', 'v': 11, 'n': 'fanspeed'}`

Should I add any other info from the logs?

**Comment by shlomki** [comment]
And since we're already digging into details, this model also offers control of a "Germ Shield" function through the app, which currently the integration doesn't support.
Here's an example from the logs (germ shield disabled):

`{'n': 'germshield', 'vb': False, 't': 1733672927}`

**Comment by dahlb** [comment]
v1.17.1 should fix the fan speed.

if you want to add support for germshield please open a new ticket
