### ISSUE TITLE
Fail to get configuration ui to show authentication

### ISSUE THREAD

**Issue by kadorken** [dahlb/ha_blueair#156]
The configuration screen just shows a ‘loading’ icon constantly, and i was expecting some form of username/password entry.
![IMG_1873](https://github.com/user-attachments/assets/a93d1479-47fb-4b21-9e58-336032851df6)

my
Home Assistant

Core
2024.12.1
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.6

**Comment by dahlb** [comment]
your screenshot seems to show an update dialog, if you want to enter credentials the only way to do that is to add the integration

**Comment by kadorken** [comment]
hmmm, i had just intalled havs and this customization. when i first saw the configuration screen, the only operation appeared to be ‘update’
i pressed that and now remain in this state,


i will have to look again next week when i return to the site

keith

On Dec 8, 2024, at 07:47, Bren Dahl ***@***.***> wrote:

﻿

your screenshot seems to show an update dialog, if you want to enter credentials the only way to do that is to add the integration

**Comment by dahlb** [comment]
Sounds like you have installed this integration into your ha platform, the next step is to add it https://www.home-assistant.io/getting-started/integration/

**Comment by kadorken** [comment]
thanks. i got lost in the steps . i think it is working now (blueair 211i max)



On Dec 8, 2024, at 10:11, Bren Dahl ***@***.***> wrote:

﻿

Sounds like you have installed this integration into your ha platform, the next step is to add it https://www.home-assistant.io/getting-started/integration/
