### ISSUE TITLE
LED settings not working with Classic_605

### ISSUE THREAD

**Issue by zwolfinger** [dahlb/ha_blueair#17]
"Failed to call service light/turn_on" 

"Failed to call service light/turn_off"

v1.7.4
HA v2023.4.6

**Comment by dahlb** [comment]
Please attach debug level logs to this issue

Troubleshooting
You can enable logging for this integration specifically and share your logs, so I can have a deep dive investigation. To enable logging, update your configuration.yaml like this, we can get more information in Configuration -> Logs page
logger:
  default: warning
  logs:
    custom_components.ha_blueair: debug
    blueair_api: debug

**Comment by dahlb** [comment]
stale
