### ISSUE TITLE
Stop forcing a restart of Home Assistant

### ISSUE THREAD

**Issue by JAAlperin** [dahlb/ha_blueair#174]
The BlueAir integration seems to be updated every day, and requires a restart of HA.  This is disruptive to other, ongoing automations and integrations.

**Comment by dahlb** [comment]
hi @JAAlperin, you are not required to update this integration everytime there is a new feature, if the update schedule is faster then you would like just ignore an update until you would like to install it, we don't require you to restart HA we are just releasing new features as they are completed
