### ISSUE TITLE
Add support for Germ Shield switch for 7440i

### ISSUE THREAD

**Issue by shlomki** [dahlb/ha_blueair#177]
It would be great if the integration could support the "Germ Shield" option which exists on the official app.

7440i appears as `'sku': '105820'` in the logs.

And here is how it looks like in the logs when Germ Shield is disabled:
`{'n': 'germshield', 'vb': False, 't': 1733672927}`

I believe all 7xxxi models support this function too (example: 7770i), but I don't have their SKUs.

Let me know if any further data is needed in order to support this feature.
Thank you for all of the amazing work on this integration!

**Comment by dahlb** [comment]
added new switch in v[1.22.0](https://github.com/dahlb/ha_blueair/commit/830919b75aaa1bb296df09c383427dd2e3cbf475)
