### ISSUE TITLE
Account temporarily locked out

### ISSUE THREAD

**Issue by waleed-source** [dahlb/ha_blueair#36]
This problem has been occurring for months and I did not find a solution for it. 

I searched for similar problems but did not find them.

 After the update, I get this message: 

> “failed to set up.”

 I looked at the log and it says 👎 

> “errorDetails”: “Account temporarily locked out.”
>    "errorMessage": "Account Temporarily Locked Out","

Is there a solution to this problem?

**Comment by waleed-source** [comment]
the Log Details (ERROR)

### This error originated from a custom integration.

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/ha_blueair/__init__.py:76
> Integration: Blueair (documentation, issues)
> First occurred: 12:25:32 PM (1 occurrences)
> Last logged: 12:25:32 PM
> 
> Error setting up entry user@mail.com for ha_blueair
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/ha_blueair/__init__.py", line 76, in async_setup_entry
>     _, aws_devices = await get_aws_devices(
>                      ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/blueair_api/util_bootstrap.py", line 56, in get_aws_devices
>     api_devices = await api.devices()
>                   ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/blueair_api/http_aws_blueair.py", line 16, in request_with_active_session_wrapper
>     return await func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/blueair_api/http_aws_blueair.py", line 164, in devices
>     "Authorization": f"Bearer {await self.get_access_token()}",
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/blueair_api/http_aws_blueair.py", line 156, in get_access_token
>     await self.refresh_access_token()
>   File "/usr/local/lib/python3.11/site-packages/blueair_api/http_aws_blueair.py", line 142, in refresh_access_token
>     await self.refresh_jwt()
>   File "/usr/local/lib/python3.11/site-packages/blueair_api/http_aws_blueair.py", line 125, in refresh_jwt
>     await self.refresh_session()
>   File "/usr/local/lib/python3.11/site-packages/blueair_api/http_aws_blueair.py", line 114, in refresh_session
>     await self._post_request_with_logging_and_errors_raised(
>   File "/usr/local/lib/python3.11/site-packages/blueair_api/http_aws_blueair.py", line 51, in request_with_errors_wrapper
>     raise LoginError(response_text)
> blueair_api.errors.LoginError: {
>   "callId": "d371f73a7cba4c82ab34b46a1e7b1dc6",
>   "errorCode": 403120,
>   "errorDetails": "Account temporarily locked out",
>   "errorMessage": "Account Temporarily Locked Out",
>   "apiVersion": 2,
>   "statusCode": 403,
>   "statusReason": "Forbidden",
>   "time": "2023-09-03T09:25:32.701Z"
> }
>

**Comment by dahlb** [comment]
that looks like an auth issue, are you able to successfully login to the blueair mobile app?

**Comment by waleed-source** [comment]
`that looks like an auth issue, are you able to successfully login to the blueair mobile app?
`
I reinstalled ((  Blueair Filters.  ))and it worked Now 
but only 5 entites
Controls
- [x] adjust fan speed, turn off/on
- [x] adjust light brightness, turn off/on
Sensors
- [x] filter replacement
- [X] child lock
- [X] Online
and the another 
- [ ] humidity
- [ ] connectivity
- [ ] temperature
- [ ] PM 1
- [ ] PM 2.5
- [ ] PM 10
- [ ] VOC 
 
But the other hack ((BlueAir Integration)) didn't work for me

**Comment by dahlb** [comment]
detailed logs, and model information might help this issue.  Though it looks like you are just hoping for more entities then your model supports ...

**Comment by waleed-source** [comment]
Yes, it supports it in the past, but after the update it did not work at all, and the problem was in the first comment. I posted the log and advised a friend to reinstall the hack.
It was able to install and accept the user, but the entities are not the same as before

The model is:-  blueair classic 280l

As for the other hackBlueAir Integration  , it still does not work :


the logs :-

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/blueair/__init__.py:50
> Integration: BlueAir (documentation, issues)
> First occurred: 7:53:35 AM (1 occurrences)
> Last logged: 7:53:35 AM
> 
> Error setting up entry BlueAir user@mail.com for blueair
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/blueair/__init__.py", line 50, in async_setup_entry
>     hass.config_entries.async_setup_platforms(entry, PLATFORMS)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
========================================
and now,  thank you for your help and acceptance of my problem

Thank you very much for what you have provided and will provide

My regards to you and your generosity

**Comment by dahlb** [comment]
please enable logging as described here https://github.com/dahlb/ha_blueair and attach the resulting logs and I will attempt to add support for that model's air quality sensors.  What other integrations don't do and their logs aren't helpful here.
