### ISSUE TITLE
LED controls do not work correctly, and LED Entity State is "Unknown" on Protect 7470i

### ISSUE THREAD

**Issue by kwbeck** [dahlb/ha_blueair#4]
@dahlb Thank you for the work on the integration, and for the Auto Mode fix in the previous release.  I've updated to v1.5.0, and Auto Mode is now working.

I'm also seeing another issue I wanted to make you aware of (also seen on v1.4.0, which was the first version I installed).

I see the following behavior:

1) The LED brightness slider works when changed in Home Assistant (i.e. the LED brightness does actually change and that change is reflected in the app), but the % is often incorrect by 1%, e.g. 10% in HA is 11% in the app.

2) The LED on/off icons in HA do turn the LED on/off, but when used to turn the LED on, the brightness goes to 100% (reflected in the app), and the slider in HA does not change from whatever it was before.

3) When the LED brightness is changed in the app, the slider in HA goes dark (i.e. set to 0%) and does not reflect what was set in the app.

4) The LED Entity state in HA never changes from "Unknown".

Screenshots attached.

Please let me know if there is any other info I can provide that would be of use.

<img width="635" alt="Blueair Device Page Screenshot 2022-07-29 155532" src="https://user-images.githubusercontent.com/98544743/181839756-3df1dcee-0906-4e8c-b09e-4bafd120f5b1.png">
<img width="239" alt="Blueair LED entity details Screenshot 2022-07-29 155626" src="https://user-images.githubusercontent.com/98544743/181839833-10a2afff-d206-41bf-811f-a485d76713bf.png">
<img width="383" alt="Blueair LED entity state Screenshot 2022-07-29 155730" src="https://user-images.githubusercontent.com/98544743/181839848-d1025bb8-8bb5-4f0c-a2fe-b8450fa6d03a.png">
s

**Comment by dahlb** [comment]
great documentation on this issue, I'll try to knock it out tomorrow :) if my toddler has a good nap

**Comment by dahlb** [comment]
I think all the symptoms listed in this ticket are addressed in https://github.com/dahlb/ha_blueair/commit/b6d81717dbd82c67b8c6c1a77af98a1e3233d43d and released in v1.5.1 please let me know if I missed anything or this is ready for be resolved

**Comment by kwbeck** [comment]
> great documentation on this issue, I'll try to knock it out tomorrow :) if my toddler has a good nap

Thank you.  I don't code, but I'm a pretty decent tester and bug writer...  :)

**Comment by kwbeck** [comment]
> I think all the symptoms listed in this ticket are addressed in [b6d8171](https://github.com/dahlb/ha_blueair/commit/b6d81717dbd82c67b8c6c1a77af98a1e3233d43d) and released in v1.5.1 please let me know if I missed anything or this is ready for be resolved

I've installed and tested the fix/new release, and everything looks great.  Thank you very much.
