### ISSUE TITLE
Enable multiple sensors for 411i Max

### ISSUE THREAD

**Issue by musicjeremy** [dahlb/ha_blueair#65]
A number of items are not showing up on my 411i Max models. I would be happy to provide info/data dumps to help you make these features work.

![Snag_dff98d1](https://github.com/dahlb/ha_blueair/assets/48184942/248077ba-e337-4245-abca-2670cb052caf)

**Comment by nickwest** [comment]
I also have a 411i Max and see similar results as @musicjeremy. However, I'm fairly sure the 411i Max only has a PM 2.5 sensor in it. In the Blueair app I also only see PM 2.5 readings. I believe this is functioning as expected. 

I think the only integration improvement would be to hide/disable those sensors if the model is 411i Max. If it helps, the device SKU of the 411i Max is 110057.

Great integration, works well!

**Comment by jonathanrobichaud4** [comment]
@nickwest is correct. There's only PM2.5 for the 411i Max. The only reason these sensors are showing up is because they are available on the models the integration was originally written for. I just went into the the entities and disabled them which works well enough. Model handling could be implemented to make sure these entities only show up on supported models but as it is right now it doesn't break anything plus it would be hard to test.

**Comment by dahlb** [comment]
I think 411i max should only have the pm25 sensor in version [1.13.0](https://github.com/dahlb/ha_blueair/commit/4fb1c12f6668ccba4ab6f18d5dd10e4ad43ccd3e) (if they were previously added they will still exist but will now have a delete button)

**Comment by jhemak** [comment]
311i Max should also have only PM25.

**Comment by dahlb** [comment]
> 311i Max should also have only PM25.

updated in v1.14.1

**Comment by jhemak** [comment]
Just grabbed 1.14.1 and PM25 is now Unavailable.  

The other 5 sensors (VOC, PM1, etc.) are still there as disabled.  When I enable they show no state nor have an option to be deleted.

**Comment by jhemak** [comment]
Just noticed this in the log:

```
Error adding entity sensor.air_purifier_pm25 for domain sensor with platform ha_blueair
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by dahlb** [comment]
> Just noticed this in the log:
> 
> ```
> Error adding entity sensor.air_purifier_pm25 for domain sensor with platform ha_blueair
> TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
> ```

1.14.2 fixes a typo that caused that error
