### ISSUE TITLE
Add night mode support

### ISSUE THREAD

**Issue by jonathanrobichaud4** [dahlb/ha_blueair#81]
Hi, 
I have a 411i that works perfectly other than the fact I can’t set night mode from the integration. Is there any way it could be added or could I help add it?

Thanks

**Comment by dahlb** [comment]
I no longer work on features I don't have the hardware to verify, but adding a switch for night mode on the 411i should be pretty straight forward.

first step would be to add the feature in https://github.com/dahlb/blueair_api which wraps the raw api and would need a new method to set the value in https://github.com/dahlb/blueair_api/blob/main/src/blueair_api/http_blueair.py finding the correct endpoint is the trickiest part and would probably require an android emulator and a jailbroken apk for blue air, mitm apk proxy is how I've done it in the past

once it is added to the api repo you can add a switch in this repo that exposes and updates the value

**Comment by jonathanrobichaud4** [comment]
I'll work on adding support to the home assistant integration now!

**Comment by jonathanrobichaud4** [comment]
Ok I have opened PR's in both repos. It seems to be working quite well right now when testing.

**Comment by dahlb** [comment]
great new feature, thanks for adding this. I made a small change to handle models like the classic series that don't have a night mode. v1.9.1

**Comment by SoccerCore11** [comment]
> finding the correct endpoint is the trickiest part and would probably require an android emulator and a jailbroken apk for blue air, mitm apk proxy is how I've done it in the past

I finally got the proxy working, but the Blueair app doesn't want to connect through the proxy. Can you give me another pointer on how to get the app to work through the proxy? I'd like to get the PM1, PM2.5, PM10, tVOC, temperature, and humidity sensors working.

> [20:27:11.202][192.168.50.18:63241] server connect 172.217.0.170:443
> [20:27:11.242][192.168.50.18:63241] Client TLS handshake failed. The client does not trust the proxy's certificate for play.googleapis.com (OpenSSL Error([('SSL routines', '', 'ssl/tls alert certificate unknown')]))
> [20:27:11.243][192.168.50.18:63241] client disconnect
> [20:27:11.244][192.168.50.18:63241] server disconnect 172.217.0.170:443
> [20:27:40.801][192.168.50.18:63263] client connect
> [20:27:40.837][192.168.50.18:63263] server connect 54.205.38.104:443
> [20:27:40.918][192.168.50.18:63263] Client TLS handshake failed. The client does not trust the proxy's certificate for api-us-east-1.blueair.io (OpenSSL Error([('SSL routines', '', 'ssl/tls alert certificate unknown')]))
> [20:27:40.919][192.168.50.18:63263] client disconnect

**Comment by jonathanrobichaud4** [comment]
What model do you have? Some don't support it like the 411i Max. Check blueair's website maybe? I also didn't use the proxy, I just used stub.py which returns a bunch of debug info in the console.

**Comment by SoccerCore11** [comment]
I have the Classic 680i, and all those sensors show in the BlueAir app. Sorry for being dense, but where do I find 'stub.py'?

**Comment by jonathanrobichaud4** [comment]
> I have the Classic 680i, and all those sensors show in the BlueAir app. Sorry for being dense, but where do I find 'stub.py'?

Sorry last reply and then I’ll leave this issue since it’s closed but it’s under the Blueair_api repository that this integration uses
