### ISSUE TITLE
Fan Speed Discrepancies for i max series

### ISSUE THREAD

**Issue by jhemak** [dahlb/ha_blueair#82]
Hello! Thanks for your work on this! I noticed with the 411i Max and 311i Max there is a discrepancy between the fan speed reported in the Blueair app and the attribute reported in HA. For example, when the fan is running at full speed, it is shown as only 91% in HA.

Here is what I found:

App -> HA
0 -> 0
12 -> 11
16 -> 15
21 -> 19
25 -> 23
30 -> 27
34 -> 31
38 -> 35
43 -> 39
47 -> 43
52 -> 47
56 -> 51
60 -> 55
65 -> 59
69 -> 63
74 -> 67
78 -> 71
82 -> 75
87 -> 79
91 -> 83
96 -> 87
100 -> 91

Any idea what is causing this and how it can be fixed?

**Comment by dahlb** [comment]
Looks like the i max series speed runs from 0-91 instead of 0-100.

I only have classic and protect series and they all run from 0-100.  

I'll leave this ticket for somebody with an i max to tackle.

**Comment by jonathanrobichaud4** [comment]
Ok so it seems like when talking just to the raw api and looking at the app the minimum is 11 (anything less is 'standby' mode) and the max is 88. It is super weird I have no idea why they did that.

**Comment by jonathanrobichaud4** [comment]
I feel like adding different model handling might be a good idea due to the variance between them @dahlb? Not sure how you'd want to implement it if at all but that can be in a separate discussion I feel

**Comment by dahlb** [comment]
these are some great insights to the i max api.  I am not inclined to add model specific handling of the raw values to try and normalize the blueair api for them, that seems likely to reduce overall reliability of the integration.  I've found my two protects each have a clear change in volume based on the % set in the api. I'd guess the same is true for most of the models, and while these insights can be helpful to others I don't think we should codify them.

**Comment by jhemak** [comment]
Thanks guys!  I believe my SKU is 110092, but if that doesn't seem right let me know how exactly you are finding it.

One other thing ... I had to make a slight tweak ... without this, I was finding that sending a speed of 15% in HA was causing the speed to get set to 14%, etc.  I also included a little hack to ensure 50% is displayed as 50% and not 51% due to rounding.  Feel free to incorporate and/or improve upon this.

```
    @property
    def percentage(self) -> int:
        """Return the current speed percentage."""
        current_speed = int(round(self._device.fan_speed / self._device.speed_count * 100))
        if current_speed == 51:
            current_speed = 50
        return current_speed

    async def async_set_percentage(self, percentage: int) -> None:
        await self._device.set_fan_speed(int(round(percentage / 100 * self._device.speed_count)))
        self.async_write_ha_state()
```

**Comment by dahlb** [comment]
@jhemak is 110092 the sku for your 411i Max or 311i Max? they should each have different sku

**Comment by jhemak** [comment]
@dahlb - yes, it's a 311i Max.  Thank you!

**Comment by dahlb** [comment]
311i max added in version 1.11.0

**Comment by jhemak** [comment]
Thank you!
