### ISSUE TITLE
2024-03-22 22:49:40.705 ERROR (MainThread) [custom_components.ha_blueair.blueair_data_update_coordinator] 'filter_status'

### ISSUE THREAD

**Issue by Flash4777** [dahlb/ha_blueair#86]
It's failing setup and does not pull in entities but in the log it pulls all my air purifiers. I and running 2024.3.3 Below is the only error I see.

2024-03-22 22:49:40.705 ERROR (MainThread) [custom_components.ha_blueair.blueair_data_update_coordinator] 'filter_status'

This error originated from a custom integration.

Logger: custom_components.ha_blueair.blueair_data_update_coordinator
Source: custom_components/ha_blueair/blueair_data_update_coordinator.py:40
integration: Blueair (documentation, issues)
First occurred: 10:19:21 PM (29 occurrences)
Last logged: 10:42:46 PM

'filter_status'

**Comment by dahlb** [comment]
release version 1.9.2 should now handle models that do not report a filter_status, not sure if that allows your models to integrate but you should no longer have the above error

**Comment by Flash4777** [comment]
So I still get the error. My air purifiers do support filter status. Maybe
I will just factory reset them all and start over.
