### ISSUE TITLE
Integration failing to load

### ISSUE THREAD

**Issue by jhemak** [dahlb/ha_blueair#91]
Hello!  For the first time today my air purifier has gone unavailable in HA and the integration will not reload.  Is anyone else having this problem?

**Comment by amorabito** [comment]
I am experiencing issues today as well, from logs:


```
This error originated from a custom integration.

Logger: custom_components.ha_blueair.blueair_aws_data_update_coordinator
Source: helpers/update_coordinator.py:347
integration: Blueair (documentation, issues)
First occurred: 6:47:08 AM (1 occurrences)
Last logged: 6:47:08 AM

Error fetching ha_blueair-Living Room Purifier data: 'NoneType' object has no attribute 'json'
```

**Comment by jonathanrobichaud4** [comment]
Same here! I'll take a look and see if they changed to api or something

**Comment by jonathanrobichaud4** [comment]
Seems like it's on blueair's end? I'm getting a 502 error but I can still control it over their app. I'd attach the console output but I don't know if there's info in there that I'd need to redact

**Comment by julio8a** [comment]
Looks like I'm not the only one! Thanks for reporting @jhemak

**Comment by Mark612** [comment]
Same issue, not loading today.

**Comment by ps5281** [comment]
I'm also having issues.

**Comment by amorabito** [comment]
And its back to working for me randomly.

**Comment by thoughtleader** [comment]
Working for me as well

**Comment by dahlb** [comment]
looks like blueair api server maintenance
